"use client";

import { useState } from "react";
import Link from "next/link";
import { trpc } from "@/lib/trpc/client";
import { useI18n } from "@/lib/i18n/client";

const skinTypeLabels: Record<string, string> = {
  oily: "Oleosa",
  dry: "Seca",
  combination: "Mista",
  normal: "Normal",
  sensitive: "Sensivel",
};

function safeParseConditions(json: string | null | undefined): string[] {
  if (!json) return [];
  try {
    const parsed = JSON.parse(json);
    if (Array.isArray(parsed)) return parsed.map((c: any) => c.name ?? c);
    return [];
  } catch {
    return [];
  }
}

type TabId = "auto" | "manual";

export default function KitsPage() {
  const { t } = useI18n();
  const [tab, setTab] = useState<TabId>("auto");
  const [copiedId, setCopiedId] = useState<string | null>(null);

  const tenantQuery = trpc.tenant.getMine.useQuery();
  const tenantSlug = tenantQuery.data?.slug ?? "";

  const autoKits = trpc.kit.listAutoGenerated.useQuery({ page: 1, pageSize: 50 });
  const manualKits = trpc.kit.list.useQuery();
  const deleteKit = trpc.kit.delete.useMutation({
    onSuccess: () => manualKits.refetch(),
  });

  function copyLink(kitLink: string, id: string) {
    const url = `${window.location.origin}/kit/${kitLink}`;
    navigator.clipboard.writeText(url).then(() => {
      setCopiedId(id);
      setTimeout(() => setCopiedId(null), 2000);
    });
  }

  function copyManualLink(kitSlug: string, id: string) {
    const url = `${window.location.origin}/kit/manual/${tenantSlug}/${kitSlug}`;
    navigator.clipboard.writeText(url).then(() => {
      setCopiedId(id);
      setTimeout(() => setCopiedId(null), 2000);
    });
  }

  return (
    <div className="p-4 md:p-8">
      <div className="flex flex-col md:flex-row md:items-start md:justify-between gap-4">
        <div>
          <h1 className="font-serif text-xl md:text-2xl text-carbone">{t.dashboardPages.kits_title}</h1>
          <p className="text-pierre text-sm font-light mt-1">
            {t.dashboardPages.kits_subtitle}
          </p>
        </div>
        <Link
          href="/dashboard/kits/novo"
          className="px-5 py-2 bg-carbone text-blanc-casse text-sm font-light tracking-wide hover:bg-terre transition-colors min-h-[44px] md:min-h-0 flex items-center"
        >
          {t.dashboardPages.kits_new_manual}
        </Link>
      </div>

      {/* Tabs — note: inner variable shadows outer `t` (i18n hook) so we
          rename the map var to tabKey */}
      <div className="flex gap-0 mt-8 border-b border-sable/20">
        {(["auto", "manual"] as TabId[]).map((tabKey) => (
          <button
            key={tabKey}
            onClick={() => setTab(tabKey)}
            className={`px-5 py-3 text-[10px] uppercase tracking-wider font-light transition-colors ${
              tab === tabKey
                ? "text-carbone border-b-2 border-carbone -mb-px"
                : "text-pierre hover:text-carbone"
            }`}
          >
            {tabKey === "auto" ? t.dashboardPages.kits_tab_auto : t.dashboardPages.kits_tab_manual}
          </button>
        ))}
      </div>

      {/* Auto-generated kits */}
      {tab === "auto" && (
        <div className="mt-6">
          {autoKits.isLoading && (
            <p className="text-pierre font-light text-sm">{t.dashboardPages.common_loading}</p>
          )}
          {autoKits.data && autoKits.data.items.length === 0 && (
            <div className="text-center py-16 bg-white border border-sable/20">
              <p className="text-pierre font-light text-sm">
                {t.dashboardPages.kits_auto_empty}
              </p>
            </div>
          )}
          {autoKits.data && autoKits.data.items.length > 0 && (
            <div className="bg-white border border-sable/20 overflow-x-auto">
              <table className="w-full">
                <thead>
                  <tr className="border-b border-sable/20 bg-ivoire/50">
                    <th className="text-left px-5 py-3 text-[10px] text-pierre uppercase tracking-wider font-light">
                      {t.dashboardPages.common_date}
                    </th>
                    <th className="text-left px-5 py-3 text-[10px] text-pierre uppercase tracking-wider font-light">
                      {t.dashboardPages.reports_th_client}
                    </th>
                    <th className="text-left px-5 py-3 text-[10px] text-pierre uppercase tracking-wider font-light">
                      {t.dashboardPages.reports_th_skin_type}
                    </th>
                    <th className="text-left px-5 py-3 text-[10px] text-pierre uppercase tracking-wider font-light">
                      {t.dashboardPages.reports_th_products}
                    </th>
                    <th className="text-right px-5 py-3 text-[10px] text-pierre uppercase tracking-wider font-light">
                      {t.dashboardPages.kits_th_total}
                    </th>
                    <th className="text-right px-5 py-3 text-[10px] text-pierre uppercase tracking-wider font-light">
                      {t.dashboardPages.common_actions}
                    </th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-sable/10">
                  {autoKits.data.items.map((analysis) => {
                    const productTotal = analysis.recommendations.reduce(
                      (sum, r) => sum + (r.product.price ?? 0),
                      0
                    );
                    const kitUrl = analysis.kitLink
                      ? `/kit/${analysis.kitLink}`
                      : null;

                    return (
                      <tr key={analysis.id} className="hover:bg-ivoire/30">
                        <td className="px-5 py-4 text-sm text-carbone font-light whitespace-nowrap">
                          {new Date(analysis.createdAt).toLocaleDateString("pt-BR")}
                        </td>
                        <td className="px-5 py-4">
                          <p className="text-sm text-carbone font-light">
                            {analysis.clientName ?? t.dashboardPages.kits_anonymous}
                          </p>
                          {analysis.clientEmail && (
                            <p className="text-xs text-pierre font-light">
                              {analysis.clientEmail}
                            </p>
                          )}
                        </td>
                        <td className="px-5 py-4 text-sm text-carbone font-light">
                          {analysis.skinType
                            ? skinTypeLabels[analysis.skinType] ??
                              analysis.skinType
                            : "—"}
                        </td>
                        <td className="px-5 py-4">
                          <div className="flex flex-wrap gap-1">
                            {analysis.recommendations.slice(0, 2).map((r) => (
                              <span
                                key={r.product.id}
                                className="text-xs px-2 py-0.5 bg-ivoire text-terre font-light"
                              >
                                {r.product.name}
                              </span>
                            ))}
                            {analysis.recommendations.length > 2 && (
                              <span className="text-xs px-2 py-0.5 bg-ivoire text-pierre font-light">
                                +{analysis.recommendations.length - 2}
                              </span>
                            )}
                          </div>
                          <p className="text-[10px] text-pierre font-light mt-1">
                            {analysis.recommendations.length}{" "}
                            {analysis.recommendations.length === 1
                              ? t.dashboardPages.kits_product_one
                              : t.dashboardPages.kits_product_many}
                          </p>
                        </td>
                        <td className="px-5 py-4 text-right text-sm text-carbone font-light whitespace-nowrap">
                          {productTotal > 0
                            ? `R$ ${productTotal.toFixed(2)}`
                            : "—"}
                        </td>
                        <td className="px-5 py-4 text-right">
                          <div className="flex items-center justify-end gap-3">
                            {analysis.kitLink && (
                              <>
                                <button
                                  onClick={() =>
                                    copyLink(analysis.kitLink!, analysis.id)
                                  }
                                  className="text-xs text-pierre hover:text-carbone font-light underline"
                                >
                                  {copiedId === analysis.id
                                    ? t.dashboardPages.kits_copied
                                    : t.dashboardPages.kits_copy_link}
                                </button>
                                <a
                                  href={kitUrl!}
                                  target="_blank"
                                  rel="noopener noreferrer"
                                  className="text-xs text-carbone hover:text-terre font-light underline"
                                >
                                  {t.dashboardPages.kits_view_kit}
                                </a>
                              </>
                            )}
                          </div>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          )}
          {autoKits.data && autoKits.data.total > 50 && (
            <p className="text-xs text-pierre font-light mt-3">
              {t.dashboardPages.kits_showing_50.replace("{total}", String(autoKits.data.total))}
            </p>
          )}
        </div>
      )}

      {/* Manual kits */}
      {tab === "manual" && (
        <div className="mt-6">
          {manualKits.isLoading && (
            <p className="text-pierre font-light text-sm">{t.dashboardPages.common_loading}</p>
          )}
          {manualKits.data && manualKits.data.length === 0 && (
            <div className="text-center py-16 bg-white border border-sable/20">
              <p className="text-pierre font-light text-sm">
                {t.dashboardPages.kits_manual_empty}
              </p>
              <Link
                href="/dashboard/kits/novo"
                className="inline-block mt-4 px-5 py-2 bg-carbone text-blanc-casse text-sm font-light tracking-wide hover:bg-terre transition-colors"
              >
                {t.dashboardPages.kits_create_first}
              </Link>
            </div>
          )}
          {manualKits.data && manualKits.data.length > 0 && (
            <div className="space-y-3">
              {manualKits.data.map((kit) => {
                const totalPrice = kit.items.reduce(
                  (sum, item) => sum + (item.product.price ?? 0),
                  0
                );
                const discountedTotal =
                  kit.discount != null && totalPrice > 0
                    ? totalPrice * (1 - kit.discount / 100)
                    : null;

                return (
                  <div
                    key={kit.id}
                    className={`p-5 bg-white border ${
                      kit.isActive
                        ? "border-sable/20"
                        : "border-sable/10 opacity-60"
                    }`}
                  >
                    <div className="flex items-start justify-between gap-4">
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-3 flex-wrap">
                          <h3 className="text-sm text-carbone">{kit.name}</h3>
                          {!kit.isActive && (
                            <span className="text-[10px] text-pierre uppercase tracking-wider font-light px-2 py-0.5 bg-ivoire">
                              {t.dashboardPages.kits_inactive}
                            </span>
                          )}
                          {kit.discount != null && (
                            <span className="text-[10px] text-terre uppercase tracking-wider font-light px-2 py-0.5 bg-ivoire">
                              {kit.discount}% off
                            </span>
                          )}
                        </div>
                        {kit.description && (
                          <p className="text-xs text-pierre font-light mt-1">
                            {kit.description}
                          </p>
                        )}
                        <div className="flex flex-wrap gap-1 mt-2">
                          {kit.items.slice(0, 3).map((item) => (
                            <span
                              key={item.id}
                              className="text-xs px-2 py-0.5 bg-ivoire text-terre font-light"
                            >
                              {item.product.name}
                            </span>
                          ))}
                          {kit.items.length > 3 && (
                            <span className="text-xs px-2 py-0.5 bg-ivoire text-pierre font-light">
                              +{kit.items.length - 3}
                            </span>
                          )}
                        </div>
                        <div className="flex items-center gap-4 mt-2">
                          <span className="text-[10px] text-pierre font-light uppercase tracking-wider">
                            {kit._count.items}{" "}
                            {kit._count.items === 1 ? t.dashboardPages.kits_product_one : t.dashboardPages.kits_product_many}
                          </span>
                          {totalPrice > 0 && (
                            <span className="text-[10px] text-pierre font-light uppercase tracking-wider">
                              {discountedTotal !== null
                                ? `R$ ${discountedTotal.toFixed(2)} ${t.dashboardPages.kits_with_discount}`
                                : `R$ ${totalPrice.toFixed(2)}`}
                            </span>
                          )}
                        </div>
                      </div>
                      <div className="flex items-center gap-3 flex-shrink-0">
                        <Link
                          href={`/dashboard/kits/${kit.id}/editar`}
                          className="text-xs text-pierre hover:text-carbone font-light underline"
                        >
                          {t.dashboardPages.common_edit}
                        </Link>
                        <button
                          onClick={() => copyManualLink(kit.slug, kit.id)}
                          className="text-xs text-pierre hover:text-carbone font-light underline"
                        >
                          {copiedId === kit.id ? t.dashboardPages.kits_copied : t.dashboardPages.kits_copy_link}
                        </button>
                        <a
                          href={`/kit/manual/${tenantSlug}/${kit.slug}`}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="text-xs text-carbone hover:text-terre font-light underline"
                        >
                          {t.dashboardPages.kits_view_kit}
                        </a>
                        {kit.isActive && (
                          <button
                            onClick={() => {
                              if (confirm(t.dashboardPages.kits_confirm_deactivate)) {
                                deleteKit.mutate({ id: kit.id });
                              }
                            }}
                            className="text-xs text-pierre hover:text-carbone font-light underline"
                          >
                            {t.dashboardPages.cat_deactivate}
                          </button>
                        )}
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
